"""PDF report generation utilities using reportlab."""
import os
import datetime
from tkinter import filedialog
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

from db.database import BASE_DIR
from models.school import get_school_info


def prompt_save_path(default_name):
    return filedialog.asksaveasfilename(
        title="Export report as PDF",
        defaultextension=".pdf",
        filetypes=[("PDF files", "*.pdf")])

REPORTS_DIR = os.path.join(BASE_DIR, "reports")


def _get_school_info():
    info = get_school_info()
    return {
        "school_name": info.get("school_name") or "SCHOOL NAME HERE",
        "motto": info.get("motto") or "",
        "address": info.get("address") or "",
        "phone": info.get("phone") or "",
        "email": info.get("email") or "",
        "logo_path": info.get("logo_path") or "",
    }


def _draw_header(c, title, subtitle=""):
    info = _get_school_info()
    width, height = A4
    margin = 15 * mm
    x = margin
    y = height - margin

    c.setFont("Helvetica-Bold", 14)
    c.drawCentredString(width / 2, y, info["school_name"])
    y -= 6 * mm
    if info["motto"]:
        c.setFont("Helvetica-Oblique", 9)
        c.drawCentredString(width / 2, y, f'"{info["motto"]}"')
        y -= 5 * mm
    if info["address"]:
        c.setFont("Helvetica", 8)
        c.drawCentredString(width / 2, y, info["address"])
        y -= 4 * mm
    if info["phone"]:
        c.setFont("Helvetica", 8)
        c.drawCentredString(width / 2, y, f"Tel: {info['phone']}")
        y -= 4 * mm
    if info["email"]:
        c.setFont("Helvetica", 8)
        c.drawCentredString(width / 2, y, f"Email: {info['email']}")
        y -= 6 * mm

    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(width / 2, y, title)
    y -= 5 * mm
    if subtitle:
        c.setFont("Helvetica", 9)
        c.drawCentredString(width / 2, y, subtitle)
        y -= 5 * mm

    c.setLineWidth(0.5)
    c.line(margin, y, width - margin, y)
    return y - 4 * mm


def _draw_footer(c, generated_by=""):
    width, height = A4
    margin = 15 * mm
    y = margin + 10 * mm
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(width / 2, y, "This is a computer-generated document.")
    y -= 4 * mm
    c.drawCentredString(width / 2, y, f"Generated On: {datetime.datetime.now().strftime('%d %B %Y')}")
    if generated_by:
        y -= 4 * mm
        c.drawCentredString(width / 2, y, f"Generated By: {generated_by}")


def _paginate_table(c, headers, rows, start_y, margin=15 * mm):
    width, height = A4
    col_widths = []
    available = width - 2 * margin
    if headers:
        col_widths = [available / len(headers)] * len(headers)
    else:
        col_widths = [available / max(1, len(rows[0]))] * max(1, len(rows[0]) if rows else 1)

    row_height = 5 * mm
    y = start_y

    c.setFont("Helvetica-Bold", 8)
    cx = margin
    for h, w in zip(headers, col_widths):
        c.drawString(cx, y, str(h))
        cx += w
    y -= row_height
    c.setLineWidth(0.3)
    c.line(margin, y, width - margin, y)
    y -= 2 * mm

    c.setFont("Helvetica", 8)
    for row in rows:
        if y < margin + 10 * mm:
            c.showPage()
            y = height - margin
            c.setFont("Helvetica-Bold", 8)
            cx = margin
            for h, w in zip(headers, col_widths):
                c.drawString(cx, y, str(h))
            y -= row_height
            c.setLineWidth(0.3)
            c.line(margin, y, width - margin, y)
            y -= 2 * mm
            c.setFont("Helvetica", 8)

        cx = margin
        for val, w in zip(row, col_widths):
            text = str(val) if val is not None else ""
            c.drawString(cx, y, text[:50])
            cx += w
        y -= row_height

    return y


def export_arrears_pdf(arrears, base_dir):
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = prompt_save_path(f"arrears_report_{timestamp}")
    if not file_path:
        return None

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    y = _draw_header(c, "Arrears Summary Report",
                     f"Generated: {datetime.datetime.now().strftime('%d %B %Y')}")

    headers = ["ID", "Full Name", "Grade", "Stream", "Admission No.", "Balance (KES)"]
    rows = []
    total = 0.0
    for a in arrears:
        rows.append([
            a["id"], a["full_name"], a["grade"],
            dict(a).get("stream", "") or "-",
            a["admission_no"] or "-",
            f"{a['balance']:,.2f}",
        ])
        total += a["balance"]

    y = _paginate_table(c, headers, rows, y)
    y -= 4 * mm
    c.setFont("Helvetica-Bold", 9)
    c.drawString(15 * mm, y, f"Total Arrears: KES {total:,.2f}")
    _draw_footer(c)
    c.showPage()
    c.save()
    return file_path


def export_income_pdf(income_data, term_name, base_dir):
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = prompt_save_path(f"income_report_{timestamp}")
    if not file_path:
        return None

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    y = _draw_header(c, "Income by Payment Method Report",
                     f"Term: {term_name}  |  Generated: {datetime.datetime.now().strftime('%d %B %Y')}")

    headers = ["Method", "Total Amount (KES)"]
    rows = []
    grand_total = 0.0
    for method, total in income_data.items():
        rows.append([method, f"{total:,.2f}"])
        grand_total += total

    y = _paginate_table(c, headers, rows, y)
    y -= 4 * mm
    c.setFont("Helvetica-Bold", 9)
    c.drawString(15 * mm, y, f"Grand Total: KES {grand_total:,.2f}")
    _draw_footer(c)
    c.showPage()
    c.save()
    return file_path


def export_students_pdf(students, base_dir):
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = prompt_save_path(f"students_report_{timestamp}")
    if not file_path:
        return None

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    y = _draw_header(c, "Students List Report",
                     f"Generated: {datetime.datetime.now().strftime('%d %B %Y')}")

    headers = ["ID", "Full Name", "Grade", "Stream", "Admission No.", "Status", "Balance (KES)"]
    rows = []
    total_balance = 0.0
    for s in students:
        rows.append([
            s["id"], s["full_name"], s["grade"],
            dict(s).get("stream", "") or "-",
            s["admission_no"] or "-",
            s["status"],
            f"{s['balance']:,.2f}",
        ])
        total_balance += s["balance"]

    y = _paginate_table(c, headers, rows, y)
    y -= 4 * mm
    c.setFont("Helvetica-Bold", 9)
    c.drawString(15 * mm, y, f"Total Students: {len(students)}  |  Total Outstanding: KES {total_balance:,.2f}")
    _draw_footer(c)
    c.showPage()
    c.save()
    return file_path


def export_payments_pdf(payments, base_dir):
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = prompt_save_path(f"payments_report_{timestamp}")
    if not file_path:
        return None

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    y = _draw_header(c, "Payments Report",
                     f"Generated: {datetime.datetime.now().strftime('%d %B %Y')}")

    headers = ["Receipt No.", "Student", "Grade", "Amount", "Method", "Date", "Received By"]
    rows = []
    total = 0.0
    for p in payments:
        rows.append([
            p["receipt_no"], p["full_name"], p["grade"],
            f"{p['amount']:,.2f}", p["method"],
            p["date_paid"], p["received_by"] or "",
        ])
        total += p["amount"]

    y = _paginate_table(c, headers, rows, y)
    y -= 4 * mm
    c.setFont("Helvetica-Bold", 9)
    c.drawString(15 * mm, y, f"Total Payments: {len(payments)}  |  Total Amount: KES {total:,.2f}")
    _draw_footer(c)
    c.showPage()
    c.save()
    return file_path
